# Generated by Django 4.2.2 on 2023-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sendmessage_alter_testimonials_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description1_ab',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description2_ab',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description3_ab',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_co',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='jobs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_po',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='description_se',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description1_sk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='description_te',
            field=models.TextField(blank=True),
        ),
    ]
